name: Test Challenge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
            node-version: 18
      - run: npm install
      - run: npm run clean
      - run: npm run build

    #
    # - name: Setup Node.js
    # uses: actions/setup-node@v3
    # with:
    #     node-version: 'lts/*'
    #     cache: 'pnpm'
    #